#!/bin/sh

# JSON Header
echo '{ "version": 1 }'

echo '[ [],' # send empty array to start

function cpu {
	CPU1=$(head -n1 /proc/stat | cut -d" " -f6)
	sleep 1;
	CPU2=$(head -n1 /proc/stat | cut -d" " -f6)
    CPU=$(bc -l <<< "scale=0; 100 - ($CPU2-$CPU1)/$(nproc)" | sed -e 's/-//')
	printf "%2d%% " $CPU
}

function memory {
    printf " $(LC_ALL=C free -h --si | awk '/Mem/{print $3}') "
}

function temperature {
    TEMP=$(sensors k10temp-pci-00c3 | sed -ne '/Tdie/{s/.*: //;p;q}')
    ITEMP=${TEMP/.*/}
    printf " %s" ${TEMP/+/}
}

function battery {
    [ -f /sys/class/power_supply/BAT1 ] || return
	local LEVEL=$(< /sys/class/power_supply/BAT1/capacity)
	local AC="\uf0e7" STATUS="\uf240"
    [ $LEVEL -lt 80 ] && STATUS="\uf241"
    [ $LEVEL -lt 50 ] && STATUS="\uf242"
    [ $LEVEL -lt 20 ] && STATUS="\uf243"
    [ $LEVEL -lt 10 ] && STATUS="\uf244"
	grep -q 1 /sys/class/power_supply/ACAD/online && STATUS=$AC
	echo -ne " ${STATUS} "
}

function sndcard {
    local card=$1 ctl=$2 on=$3 off=$4
    LEVEL=$(amixer -c $card get $ctl | tail -n1) || return
	fgrep -q '[on]' <<< $LEVEL && echo -n " $on " || printf " $off "
	echo -n $(egrep -o '[0-9]+%' <<< $LEVEL)
}

function sound {
    sndcard Generic Master '\ue050' '\ue050'
    sndcard Generic Headphone '\ue023' '\ue023'
    sndcard SE Speaker '\ue311' '\ue310'
}

function full_status () {
	cpu; temperature; memory; sound; echo -ne "$(date '+%a, %d %b %H:%M')"
}

while true; do
	echo -n "[{\"name\":\"time\",\"align\":\"left\",\"full_text\":\"$(full_status)\"}],"
done

# vim:ts=4:sw=4:et:
